services:
  - type: web
    name: gcc-car-value-api
    runtime: docker
    repo: https://github.com/saarimabdulrahman-hub/gcc-car-value.git
    branch: feature-url-valuation
    rootDir: .
    dockerfilePath: docker/Dockerfile.api
    healthCheckPath: /v1/health
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_URL_SYNC
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ENVIRONMENT
        value: production
