"""Haraj CSS selectors — Arabic-first with English fallbacks."""

from browser.selectors.group import create_selector

# Haraj selectors support both Arabic and English class names
_HARAJ_SELECTORS = [
    # Search results
    create_selector("haraj.card", "[class*='post'], [class*='listing'], [class*='advert']",
                    fallbacks=["article", "[class*='card']", "li"],
                    marketplace="haraj", group="listing", description="Haraj listing card"),
    create_selector("haraj.card.link", "a[href*='/haraj/']",
                    fallbacks=["a[href*='cars']", "h3 a"],
                    marketplace="haraj", group="listing", selector_type="url"),
    create_selector("haraj.card.title", "h3, [class*='title'], [class*='عنوان']",
                    fallbacks=["a[class*='post']"],
                    marketplace="haraj", group="title"),
    create_selector("haraj.card.price", "[class*='price'], [class*='سعر']",
                    fallbacks=["[class*='amount']", "strong"],
                    marketplace="haraj", group="price", selector_type="currency"),
    create_selector("haraj.card.year", "[class*='year'], [class*='سنة']",
                    fallbacks=["[class*='model']"],
                    marketplace="haraj", group="year", selector_type="year"),
    create_selector("haraj.card.mileage", "[class*='mileage'], [class*='كم']",
                    fallbacks=["[class*='km']", "[class*='ممشى']"],
                    marketplace="haraj", group="mileage", selector_type="integer"),
    create_selector("haraj.card.location", "[class*='location'], [class*='مدينة']",
                    fallbacks=["[class*='city'], [class*='region']"],
                    marketplace="haraj", group="location"),
    create_selector("haraj.pagination.next", "a[class*='next'], a[rel='next']",
                    fallbacks=["a:contains('التالي')", "a:contains('Next')"],
                    marketplace="haraj", group="listing"),

    # Detail page
    create_selector("haraj.detail.title", "h1, [class*='title'], [class*='عنوان']",
                    fallbacks=["[class*='main-title']"],
                    marketplace="haraj", group="title"),
    create_selector("haraj.detail.price", "[class*='price'], [class*='سعر']",
                    fallbacks=["[class*='amount']"],
                    marketplace="haraj", group="price", selector_type="currency"),
    create_selector("haraj.detail.mileage", "[class*='mileage'], [class*='كم']",
                    fallbacks=["[class*='km'], [class*='ممشى']"],
                    marketplace="haraj", group="mileage", selector_type="integer"),
    create_selector("haraj.detail.year", "[class*='year'], [class*='سنة']",
                    fallbacks=["[class*='model-year']"],
                    marketplace="haraj", group="year", selector_type="year"),
    create_selector("haraj.detail.spec", "[class*='spec'], [class*='مواصفات']",
                    fallbacks=["[class*='regional'], [class*='استيراد']"],
                    marketplace="haraj", group="spec"),
    create_selector("haraj.detail.transmission", "[class*='transmission'], [class*='ناقل']",
                    fallbacks=["[class*='gear'], [class*='جير']"],
                    marketplace="haraj", group="transmission"),
    create_selector("haraj.detail.fuel", "[class*='fuel'], [class*='وقود']",
                    fallbacks=["[class*='بنزين']"],
                    marketplace="haraj", group="fuel"),
    create_selector("haraj.detail.body", "[class*='body'], [class*='نوع']",
                    fallbacks=["[class*='category']"],
                    marketplace="haraj", group="body_type"),
    create_selector("haraj.detail.color", "[class*='color'], [class*='لون']",
                    fallbacks=["[class*='exterior']"],
                    marketplace="haraj", group="color"),
    create_selector("haraj.detail.description", "[class*='description'], [class*='وصف']",
                    fallbacks=["[class*='body-text'], [class*='details']"],
                    marketplace="haraj", group="description"),
    create_selector("haraj.detail.seller", "[class*='seller'], [class*='بائع']",
                    fallbacks=["[class*='member'], [class*='معلن']"],
                    marketplace="haraj", group="seller"),
    create_selector("haraj.detail.images", "[class*='gallery'] img, [class*='slider'] img",
                    fallbacks=["[class*='photo'] img", "img[src*='haraj']"],
                    marketplace="haraj", group="images"),
]
